name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    # name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # this is only needed while `bun publish` is not yet available (npm publish is used instead)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Use Cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            node-modules-

      - name: Install Dependencies
        run: bun install

      - name: Publish Framework
        run: ./storage/framework/scripts/publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish Dummy Libraries
        run: bunx pnpm --filter='./storage/framework' publish:dummy-libs
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # temporary workaround until npm publish is replaced with bun publish
      - name: Install VS Code Extension Dependencies
        run: cd storage/framework/ide/vscode && bun install && cd ../../../../

      # TODO: remove npm once bun publish is available
      - name: Publish VS Code Extension
        run: cd storage/framework/ide/vscode && npm run release && cd ../../../../
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create GitHub Release
        run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
