name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # this is only needed while `bun publish` is not yet available (npm publish is used instead)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Use cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            nodeModules-

      - name: Install Dependencies
        run: bun install

      - name: Set Application Key
        run: bun buddy key:generate

      - name: Prepublish # these packages are required for the "Publish framework" step
        run: bunx pnpm --filter='./storage/framework' build

      - name: Publish framework
        run: ./storage/framework/scripts/publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish dummy libraries
        run: bunx pnpm --filter='./storage/framework' publish:dummy-libs
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish VS Code Extension
        run: bunx pnpm --filter='./storage/framework/ide/vscode' release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create GitHub release
        run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
